server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://root:WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE@maglev.proxy.rlwy.net:12850/clothingshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE
  jpa:
    show-sql: no
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: oganiboss11@gmail.com
    password: ydgndwjksuihurub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  vnpay:
    tmn-code: TROHKPHO
    secret-key: QKX2FE5Z3B8TRU4QE1I9GQTI8E05OE2H
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    order-type: other
api:
  prefix: api/v1
jwt:
  expiration: 86400
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=