server:
  port: 8088
spring:
  datasource:
    # url: jdbc:mysql://root:WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE@maglev.proxy.rlwy.net:12850/clothingshop
    url: jdbc:mysql://localhost:3306/clothingshop?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    username: root
    # password: WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE
    password: 20112004
  jpa:
    show-sql: no
=======
    username: ${DB_USERNAME}
    # password: WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
>>>>>>> 92c514853ae7da003171660fc573c9d5312c180c
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
<<<<<<< HEAD
    username: oganiboss11@gmail.com
    password: ydgndwjksuihurub
=======
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
>>>>>>> 92c514853ae7da003171660fc573c9d5312c180c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sendgrid:
<<<<<<< HEAD
    api-key: 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
    from-email: hoductuyenqp@gmail.com
  cloudinary:
    api-key: 794879747219491
    api-secret: FWuxg7Zf3kg9uwonLtBQ5AbeYqY
  vnpay:
    tmn-code: M5O0LLB4
    secret-key: 5AG7WNH6INYKSRY4PB3XHI2BIWM2FSSV
=======
    api-key: ${SENDGRID_API_KEY}
    from-email: hoductuyenqp@gmail.com
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
>>>>>>> 92c514853ae7da003171660fc573c9d5312c180c
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8088/api/v1/payment/vn-pay-callback
    # return-url: http://clothingecommercewebsite.onrender.com/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    order-type: other
api:
  prefix: api/v1
openapi:
  service:
    api-docs: api-service
    server: http://localhost:8088
    title: API Service
    version: 1.0.0
jwt:
  accesstoken-expiration: 3600
  refreshtoken-expiration: 86400
<<<<<<< HEAD
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
=======
  secretKey: ${JWT_SECRET_KEY}
>>>>>>> 92c514853ae7da003171660fc573c9d5312c180c
