server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://root:WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE@maglev.proxy.rlwy.net:12850/clothingshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WxxYnviAdTLJKHpsvBnPvMsxtIicyAGE
  jpa:
    show-sql: no
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: oganiboss11@gmail.com
    password: ydgndwjksuihurub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sendgrid:
    api-key: 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
    from-email: hoductuyenqp@gmail.com
  cloudinary:
    api-key: 794879747219491
    api-secret: FWuxg7Zf3kg9uwonLtBQ5AbeYqY
  vnpay:
    tmn-code: M5O0LLB4
    secret-key: 5AG7WNH6INYKSRY4PB3XHI2BIWM2FSSV
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    # return-url: http://localhost:8088/api/v1/payment/vn-pay-callback
    return-url: http://clothingecommercewebsite.onrender.com/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    order-type: other
api:
  prefix: api/v1
jwt:
  accesstoken-expiration: 64000
  refreshtoken-expiration: 64000
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=